export const REALITY_BET_ABI = [
  {
    type: "function",
    name: "create_market",
    inputs: [
      { name: "title", type: "string" },
      { name: "description", type: "string" },
      { name: "resolution_url", type: "string" },
      { name: "category", type: "string" },
      { name: "close_time", type: "uint256" },
      { name: "resolve_time", type: "uint256" },
    ],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "lock_market",
    inputs: [{ name: "market_id", type: "string" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "void_market",
    inputs: [{ name: "market_id", type: "string" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "fund_market",
    inputs: [{ name: "market_id", type: "string" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "place_bet",
    inputs: [
      { name: "market_id", type: "string" },
      { name: "side", type: "string" },
    ],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "claim_winnings",
    inputs: [{ name: "bet_id", type: "string" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "refund_void",
    inputs: [{ name: "bet_id", type: "string" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "request_resolution",
    inputs: [{ name: "market_id", type: "string" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "force_resolve",
    inputs: [
      { name: "market_id", type: "string" },
      { name: "outcome", type: "string" },
      { name: "note", type: "string" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "raise_dispute",
    inputs: [
      { name: "market_id", type: "string" },
      { name: "reason", type: "string" },
    ],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "resolve_dispute",
    inputs: [
      { name: "dispute_id", type: "string" },
      { name: "upheld", type: "bool" },
      { name: "new_outcome", type: "string" },
      { name: "note", type: "string" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "re_resolve",
    inputs: [{ name: "market_id", type: "string" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "set_fee",
    inputs: [{ name: "bps", type: "uint256" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transfer_ownership",
    inputs: [{ name: "new_owner", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "get_market",
    inputs: [{ name: "market_id", type: "string" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "id", type: "string" },
          { name: "creator", type: "string" },
          { name: "title", type: "string" },
          { name: "description", type: "string" },
          { name: "resolution_url", type: "string" },
          { name: "category", type: "string" },
          { name: "close_time", type: "uint256" },
          { name: "resolve_time", type: "uint256" },
          { name: "outcome", type: "string" },
          { name: "status", type: "string" },
          { name: "pool_yes", type: "uint256" },
          { name: "pool_no", type: "uint256" },
          { name: "fee_bps", type: "uint256" },
          { name: "resolved_at", type: "uint256" },
          { name: "resolver_note", type: "string" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "get_bet",
    inputs: [{ name: "bet_id", type: "string" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "id", type: "string" },
          { name: "market_id", type: "string" },
          { name: "bettor", type: "string" },
          { name: "side", type: "string" },
          { name: "amount", type: "uint256" },
          { name: "claimed", type: "bool" },
          { name: "placed_at", type: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "get_dispute",
    inputs: [{ name: "dispute_id", type: "string" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "id", type: "string" },
          { name: "market_id", type: "string" },
          { name: "raised_by", type: "string" },
          { name: "reason", type: "string" },
          { name: "resolved", type: "bool" },
          { name: "outcome", type: "string" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "get_market_bets",
    inputs: [{ name: "market_id", type: "string" }],
    outputs: [{ name: "", type: "string[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "get_odds",
    inputs: [{ name: "market_id", type: "string" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "yes", type: "uint256" },
          { name: "no", type: "uint256" },
          { name: "pool_yes", type: "uint256" },
          { name: "pool_no", type: "uint256" },
          { name: "total_pool", type: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "get_market_stats",
    inputs: [{ name: "market_id", type: "string" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "market_id", type: "string" },
          { name: "title", type: "string" },
          { name: "status", type: "string" },
          { name: "outcome", type: "string" },
          { name: "pool_yes", type: "uint256" },
          { name: "pool_no", type: "uint256" },
          { name: "total_bets", type: "uint256" },
          { name: "yes_bets", type: "uint256" },
          { name: "no_bets", type: "uint256" },
          { name: "resolver_note", type: "string" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "get_platform_stats",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "total_markets", type: "uint256" },
          { name: "total_volume", type: "uint256" },
          { name: "fee_bps", type: "uint256" },
          { name: "owner", type: "string" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "get_bettor_bets",
    inputs: [{ name: "bettor", type: "string" }],
    outputs: [{ name: "", type: "string[]" }],
    stateMutability: "view",
  },
] as const;
